// MultiFunctionTest.idl : MultiFunctionTest.exe 的类型库源

// 此文件将由 MIDL 编译器处理以产生
// 类型库(MultiFunctionTest.tlb)。

[ uuid(BAC6CEA6-AE3C-4158-9D1D-AA2C73B5C69D), version(1.0) ]
library MultiFunctionTest
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	//  CMultiFunctionTestDoc 的主调度接口
	
	[ uuid(7758285C-48C3-4708-924A-B67530A06E9A) ]
	dispinterface IMultiFunctionTest
	{
		properties:
			
		methods:
	};

	//  CMultiFunctionTestDoc 的类信息
	
	[ uuid(23048D30-9CE3-4961-9E02-3A2CDCC449DC) ]
	coclass CMultiFunctionTestDoc
	{
		[default] dispinterface IMultiFunctionTest;
	};
};
